### ISSUE TITLE
shouldn't the functions be displayed?

### ISSUE THREAD

**Issue by bnicenboim** [spinkney/helpful_stan_functions#55]
Hi, I just discovered this, it looks super useful!

However,  I navigated through https://spinkney.github.io/helpful_stan_functions/, but the functions are never displayed, just the name and the description. Shouldn't the Stan code be displayed?

**Comment by spinkney** [comment]
Maybe? Normally the documentation doesn't contain the function internals. Think of R documentation or even Stan.

I can see how you'd want this to learn though. However, I hope that the examples and repo is enough. I'm using the documentation more for the math and references component.

**Comment by bnicenboim** [comment]
ok, I see, but a link to the "source" would be very useful at least. Otherwise one needs to navigate back and forth between the website and the github repo.

**Comment by spinkney** [comment]
Yea, that makes sense and would be good to have 👍

**Comment by spinkney** [comment]
Luckily, this is going to be easy.

Here's one example: https://spinkney.github.io/helpful_stan_functions/group__logical__array.html.

I plan to add the link to the stan file and example(s). If there are multiple languages then they'll each get a link in the documentation.

**Comment by bnicenboim** [comment]
great!! thank you!

**Comment by spinkney** [comment]
I found out that it's easy to include the source code. All the files have been updated. This is better in case I ever decide to reorganize the structure or if the github links change.
